<a href="https://colab.research.google.com/github/Jacques-Wolbeck/Processamento-Digital-Imagens-UFAL/blob/main/atividades/numpy_tutorial/quest_numpy_matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from numpy import linalg as LA


#The maximum value from given matrix
matrix = np.matrix('[9, 2; 8, 3]')
print(matrix.max())

#The minimum value from given matrix
print(matrix.min())

#the number of rows and columns of a given matrix using NumPy
matrix1 = np.arange(1,22).reshape((3, 7))
print(matrix1.shape)

#Select the elements from a given matrix
print(matrix.take(0,1))

#The sum of values in a matrix
print(matrix.sum())

9
2
(3, 7)
[[9 8]]
22


In [ ]:
#The sum of the diagonal elements of a NumPy array
array = np.array([[67, 25, 15],
                    [30, 14, 2],
                    [11, 125, 83],
                   ])
print(np.trace(array))

#Adding and Subtracting Matrices in Python
a = np.array([[1, 2], [3, 4]])
b = np.array([[4, 5], [6, 7]])

print(np.add(a,b))

#Matrix Multiplication in NumPy
print(np.dot(a,b))

#Get the eigen values of a matrix
print(LA.eigvals([[1, 2], [3, 4]]))

#Calculate the determinant of a matrix using NumPy
print(int(np.linalg.det(a)))


164
[[ 5  7]
 [ 9 11]]
[[16 19]
 [36 43]]
[-0.37228132  5.37228132]
-2


In [ ]:
# Calculating the inverse of the matrix
matrix = np.array([[-9, 2, 1],
              [8, -2, 5],
              [5, 1, 0]])
print(np.linalg.inv(matrix))

#Multiply matrices of complex numbers using NumPy in Python
x = np.array([5+3j, 5+5j])
y = np.array([2+9j, 1+2j])

print(np.vdot(x, y))

[[-0.04424779  0.00884956  0.10619469]
 [ 0.22123894 -0.04424779  0.46902655]
 [ 0.15929204  0.16814159  0.01769912]]
(52+44j)


In [ ]:
#Compute the covariance matrix of two given NumPy arrays
array1 = np.array([3, 1, 6])
array2 = np.array([8, 4, 2])

print(np.cov(array1, array2))

#Compute the Kronecker product of two mulitdimension NumPy arrays
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

print(np.kron(array1, array2))

#Convert the matrix into a list
matrix= np.matrix('[1, 2, 3, 4]')
print(matrix.tolist())


[[ 6.33333333 -3.33333333]
 [-3.33333333  9.33333333]]
[[ 5  6 10 12]
 [ 7  8 14 16]
 [15 18 20 24]
 [21 24 28 32]]
[[1, 2, 3, 4]]
