<a href="https://colab.research.google.com/github/Jacques-Wolbeck/Processamento-Digital-Imagens-UFAL/blob/main/atividades/numpy_tutorial/quest_numpy_indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

#Replace NumPy array elements that doesn’t satisfy the given condition
array = np.array([67, 34, 21, 12, 13])
array[array < 30.] = 1

print(array)

#Return the indices of elements where the given condition is satisfied
a = np.where(array > 13)
print(array[a])

#Replace negative value with zero in numpy array
array = np.array([-1, 2, 3, 4, 5, -6])
print(np.where(array < 0, 0, array))

[67 34  1  1  1]
[67 34]
[0 2 3 4 5 0]


In [ ]:
#Find indices of elements equal to zero in a NumPy array
array = np.array([  [0, 1, 2],
                    [3, 4, 0],
                    [6, 7, 0]])
print(np.argwhere(array == 0))

#Remove columns in Numpy array that contains non-numeric values
array = np.array([[2, 5, np.nan],
                  [8, 9, np.nan]])
  
print(array[:, ~np.isnan(array).any(axis=0)])

#Access different rows of a multidimensional NumPy array
array = np.array([[221, 10, 3, 10], 
                [40, 5, 266, 7], 
                [33, 428, 9, 12]])
print(array[1])

#Get row numbers of NumPy array having element larger than X
x = 78
print(np.where(np.any(array > x, axis = 1)))

[[0 0]
 [1 2]
 [2 2]]
[[2. 5.]
 [8. 9.]]
[ 40   5 266   7]
(array([0, 1, 2]),)


In [ ]:
#Get filled the diagonals of NumPy array
np.fill_diagonal(array, 5)
print(array)

#Check elements present in the NumPy array
array1 = np.array([1, 2, 3, 4, 5])
array2 = [1, 3, 5]
print(np.isin(array1, array2))

#Combined array index by index
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
  
print(np.dstack((array1, array2)))

[[  5  10   3  10]
 [ 40   5 266   7]
 [ 33 428   5  12]]
[ True False  True False  True]
[[[1 4]
  [2 5]
  [3 6]]]
