<a href="https://colab.research.google.com/github/Jacques-Wolbeck/Processamento-Digital-Imagens-UFAL/blob/main/atividades/numpy_tutorial/quest_numpy_sorting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


#Get the indices of the sorted array using NumPy in Python
array = np.array([1, 2, 3, 4, 5])
print(array)
idx = np.argsort(array)
print(idx)


#Finding the k smallest values of a NumPy array
array = np.array([67, 11, 2, 6, 8, 10, 45])
k = 3
result = np.argpartition(array, k)
  
print("k = ",k)
print(array[result[:k]])

[1 2 3 4 5]
[0 1 2 3 4]
k =  3
[6 2 8]


In [ ]:
#Get the n-largest values of an array using NumPy
array = np.array([3, 1,  0, 5, 4, 4, 9])

sorted_index_array = np.argsort(array)
sorted_array = array[sorted_index_array]
  
print("Sorted array:", sorted_array)
n = 4
result = sorted_array[-n : ]
  
print("{} largest value:".format(n), result)

#Sort the values in a matrix
matrix = np.matrix('[8, 0, 2; 11, 30, 12; 43, 25, 16]')
matrix.sort()
print(matrix)

#Find the indices into a sorted array
array = [1, 2, 3, 4, 5]
num = [3, 8, 0]

idx = np.searchsorted(array, num)
print (idx)


Sorted array: [0 1 3 4 4 5 9]
4 largest value: [4 4 5 9]
[[ 0  2  8]
 [11 12 30]
 [16 25 43]]
[2 5 0]
