<a href="https://colab.research.google.com/github/Jacques-Wolbeck/Processamento-Digital-Imagens-UFAL/blob/main/atividades/numpy_tutorial/quest_numpy_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

#Array filled with all zeros
zeros = np.zeros((3,3), dtype = int)
#Array filled with all ones
ones = np.ones((3,3), dtype = int)

print(ones)
print(zeros)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
#Check whether a Numpy array contains a specified row
array = np.array([[1,2,3],
                 [3,3,5],
                 [6,1,8]])
print([3,6,5] in array.tolist())

#Remove rows in Numpy array that contains non-numeric values
nan_array = np.array([[9, 5, 8],
                  [9, np.nan, np.nan]])
  
print(nan_array[~np.isnan(nan_array).any(axis=1)])

#The number of occurrences of a sequence in a NumPy array
print(repr(array).count("3"))

False
[[9. 5. 8.]]
3


In [ ]:
#The most frequent value in a NumPy array
x = np.array([2,2,2,2,5,5,6,43,21,2])
print(np.bincount(x).argmax())

#Combining a one and a two-dimensional NumPy Array
array_1d = np.arange(6)
array_2d = np.arange(18).reshape(3,6)
  
for a, b in np.nditer([array_1d, array_2d]):
    print("%d:%d" % (a, b),)

#add a border around a NumPy array
array = np.ones((2, 2))

array = np.pad(array, pad_width=1, mode='constant',
               constant_values=0)
print(array)

2
0:0
1:1
2:2
3:3
4:4
5:5
0:6
1:7
2:8
3:9
4:10
5:11
0:12
1:13
2:14
3:15
4:16
5:17
[[0. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]]


In [ ]:
#Compare two NumPy arrays
a = np.array([10, 99, 79])
b = np.array([87, 43, 145])

print("a >= b")
print(np.greater_equal(a, b))

#Check whether specified values are present in NumPy array
print(10 in a)

#Flatten a Matrix in Python using NumPy
arr = np.array([[8, 3], 
                [1, 9]])
  
flatten_arr = arr.flatten()
print(flatten_arr)

#Move axes of an array to new positions
arr = np.zeros((1, 2, 3, 4))
arr1 = np.moveaxis(arr, 0, -1).shape 
print(arr1)

a >= b
[False  True False]
True
[8 3 1 9]
(2, 3, 4, 1)


In [ ]:
#Move axes of an array to new positions
arr = np.zeros((1, 2, 3, 4))
arr1 = np.moveaxis(arr, 0, -1).shape 
print(arr1)

#Interchange two axes of an array
arr = np.array([[2, 4, 6]])
arr1 = np.swapaxes(arr, 0, 1)
print(arr1)

#Counts the number of non-zero values in the array
arr = [[0, 3, 9, 5, 0],
       [0, 5, 63, 21, 7]]
arr1 = np.count_nonzero(arr)
print(arr1)

#Count the number of elements along a given axis
arr = np.array([[7, 2, 1, 4], 
                [1, 1, 2, 8]])
print(np.size(arr, 0))

#Trim the leading and/or trailing zeros from a 1-D array
arr = np.array((6, 0, 0, 2, 1, 0, 7, 0, 6, 2, 9, 0, 10, 8, 0))
print(np.trim_zeros(arr))

#Change data type of given numpy array
arr = arr.astype('float64')
print(arr)

#Make a NumPy array read-only
arr.flags.writeable = False

(2, 3, 4, 1)
[[2]
 [4]
 [6]]
7
2
[ 6  0  0  2  1  0  7  0  6  2  9  0 10  8]
[ 6.  0.  0.  2.  1.  0.  7.  0.  6.  2.  9.  0. 10.  8.  0.]
